name: Contract Testing Pipeline

on:
  push:
    branches:
      - audit

  pull_request:
    branches:
      - master

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: Install Git
        run: sudo apt install git -y
      - name: Install python and pip
        run: sudo apt install python pip
      - name: Install pytezos and pytest
        run: pip install pytezos pytest
      - name: Compile contracts:
        run: ./integration_tests/build.sh
      - name: Run scenario tests
        run: pytest -s -v